name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Vite app
        run: npm run build
        working-directory: ./frontend
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob delete-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --source ${{ secrets.WEB_CONTAINER }} &&
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode key \
              --destination ${{ secrets.WEB_CONTAINER }} \
              --source ./frontend/dist \
              --overwrite
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
